import React,{useEffect,useState}from'react'
import{Check,Loader2,Radio,Server,ShieldCheck}from'lucide-react'
import{secureApi}from'../lib/supabase'

export function HardwareConfigModal({close,notify}){
 const[form,setForm]=useState({routerType:'mikrotik',integrationMode:'radius',routerAddress:'',controllerUrl:'',routerIdentity:'',apiUsername:'',apiSecret:'',enabled:false}),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{secureApi('/api/hardware/config').then(data=>{if(data)setForm(current=>({...current,routerType:data.router_type,integrationMode:data.integration_mode,routerAddress:data.router_address||'',controllerUrl:data.controller_url||'',routerIdentity:data.router_identity||'',apiUsername:data.api_username||'',enabled:data.enabled}))}).catch(e=>{if(!e.message.includes('not found'))setError(e.message)}).finally(()=>setLoading(false))},[])
 const update=e=>setForm({...form,[e.target.name]:e.target.type==='checkbox'?e.target.checked:e.target.value})
 const save=async e=>{e.preventDefault();setBusy(true);setError('');try{await secureApi('/api/hardware/config',{method:'PUT',body:JSON.stringify(form)});notify('Physical router configuration saved.');close()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal booking-modal hardware-modal"><button className="modal-close" onClick={close}>×</button><p className="eyebrow">PHYSICAL NETWORK</p><h2><Radio/> Router integration</h2><p>Use central RADIUS for private MikroTik routers, or a public HTTPS controller webhook.</p>{loading?<div className="drawer-loading"><Loader2 className="spin"/>Loading configuration…</div>:<form onSubmit={save} className="hardware-form"><div className="form-grid"><label><span>Router type</span><select name="routerType" value={form.routerType} onChange={update}><option value="mikrotik">MikroTik</option><option value="openwrt">OpenWrt</option><option value="unifi">UniFi</option><option value="other">Other</option></select></label><label><span>Integration mode</span><select name="integrationMode" value={form.integrationMode} onChange={update}><option value="radius">FreeRADIUS (recommended)</option><option value="controller_webhook">HTTPS controller webhook</option></select></label><label className="full"><span>Router identity / NAS identifier</span><input required name="routerIdentity" value={form.routerIdentity} onChange={update} placeholder="LBK-HOST-ROUTER-01"/></label><label className="full"><span>Router IP / management address</span><input name="routerAddress" value={form.routerAddress} onChange={update} placeholder="192.168.88.1 (stored for reference; not called from Vercel)"/></label>{form.integrationMode==='controller_webhook'&&<><label className="full"><span>Public controller API URL (HTTPS)</span><input required type="url" name="controllerUrl" value={form.controllerUrl} onChange={update} placeholder="https://router-controller.example.com/vouchers"/></label><label><span>API username</span><input name="apiUsername" value={form.apiUsername} onChange={update}/></label><label><span>API secret/token</span><input type="password" name="apiSecret" value={form.apiSecret} onChange={update} placeholder="Leave blank to keep existing"/></label></>}</div><label className="hardware-enable"><input type="checkbox" name="enabled" checked={form.enabled} onChange={update}/><span><b>Enable physical provisioning</b><small>Only enable after RADIUS/controller testing succeeds.</small></span></label><div className="hardware-note"><ShieldCheck/><span>Credentials are encrypted with AES-256-GCM. Private router IPs require a RADIUS/VPN bridge; Vercel cannot directly reach your LAN.</span></div>{error&&<p className="form-error">{error}</p>}<button className="primary wide" disabled={busy}>{busy?<Loader2 className="spin"/>:<><Check/>Save hardware configuration</>}</button></form>}</div></div>
}
