import React, { useEffect, useMemo, useState } from 'react'
import { Check, Headphones, Inbox, Loader2, MessageCircle, Send, TicketCheck, Wallet, X } from 'lucide-react'
import { secureApi, supabase } from '../lib/supabase'

function Shell({ children, close, wide=false }) {
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className={`modal feature-modal ${wide?'booking-modal':''}`}><button className="modal-close" onClick={close}><X/></button>{children}</div></div>
}

export function ProductionTopUp({ close }) {
  const [amount,setAmount]=useState(5000), [busy,setBusy]=useState(false), [error,setError]=useState('')
  const pay=async()=>{setBusy(true);setError('');try{const result=await secureApi('/api/payments/initialize',{method:'POST',body:JSON.stringify({amount})});window.location.assign(result.authorizationUrl)}catch(e){setError(e.message);setBusy(false)}}
  return <Shell close={close}><div className="modal-icon"><Wallet/></div><h2>Add money securely</h2><p>Pay by card, bank transfer or USSD through Paystack.</p><div className="amount-input"><span>₦</span><input type="number" min="100" max="1000000" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></div><div className="quick-amounts">{[1000,2000,5000,10000].map(n=><button key={n} className={amount===n?'active':''} onClick={()=>setAmount(n)}>₦{n.toLocaleString()}</button>)}</div>{error&&<p className="form-error">{error}</p>}<button className="primary wide" disabled={busy} onClick={pay}>{busy?<Loader2 className="spin"/>:`Continue to Paystack`}</button></Shell>
}

export function MessageHostModal({ session, currentUserId, close }) {
  const [messages,setMessages]=useState([]),[text,setText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const hostId=session.host_id||session.hostId; const receiverId=session.hosts?.user_id||session.hostOwnerId
  useEffect(()=>{let channel;secureApi(`/api/messages?hostId=${hostId}`).then(setMessages).catch(e=>setError(e.message));secureApi('/api/messages/read',{method:'PATCH',body:JSON.stringify({hostId})}).catch(()=>{});if(supabase){channel=supabase.channel(`host-chat:${hostId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`host_id=eq.${hostId}`},({new:row})=>{if(row.sender_id===currentUserId||row.receiver_id===currentUserId)setMessages(old=>old.some(m=>m.id===row.id)?old:[...old,row])}).subscribe()}return()=>{if(channel)supabase.removeChannel(channel)}},[hostId,currentUserId])
  const send=async(e)=>{e.preventDefault();if(!text.trim())return;setBusy(true);try{const row=await secureApi('/api/messages',{method:'POST',body:JSON.stringify({text,hostId,receiverId,sessionId:session.id})});setMessages(old=>old.some(m=>m.id===row.id)?old:[...old,row]);setText('')}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <Shell close={close} wide><p className="eyebrow">ACTIVE HOTSPOT</p><h2><MessageCircle size={21}/> Message Host</h2><p>{session.hosts?.business_name||session.hostName}</p><div className="chat-feed">{messages.map(m=><div key={m.id} className={`chat-bubble ${m.sender_id===currentUserId?'mine':''}`}><span>{m.text}</span><small>{new Date(m.timestamp).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></div>)}{!messages.length&&!error&&<div className="chat-empty">Ask the host about power, signal, or connection issues.</div>}</div>{error&&<p className="form-error">{error}</p>}<form className="chat-compose" onSubmit={send}><input value={text} maxLength={2000} onChange={e=>setText(e.target.value)} placeholder="Type a message…"/><button disabled={busy||!text.trim()}><Send/></button></form></Shell>
}

export function HostInbox({ currentUserId }) {
  const [messages,setMessages]=useState([]),[selected,setSelected]=useState(null),[text,setText]=useState('')
  useEffect(()=>{let channel;secureApi('/api/messages/inbox').then(setMessages).catch(()=>{});if(supabase)channel=supabase.channel('host-inbox').on('postgres_changes',{event:'INSERT',schema:'public',table:'messages'},({new:row})=>setMessages(old=>[row,...old.filter(m=>m.id!==row.id)])).subscribe();return()=>{if(channel)supabase.removeChannel(channel)}},[])
  const rooms=useMemo(()=>{const map=new Map();messages.forEach(m=>{const guest=m.sender_id===currentUserId?m.receiver_id:m.sender_id;if(!map.has(guest))map.set(guest,{guest,last:m,unread:0});if(m.receiver_id===currentUserId&&!m.read_at)map.get(guest).unread++});return [...map.values()]},[messages,currentUserId])
  const roomMessages=selected?messages.filter(m=>m.sender_id===selected||m.receiver_id===selected).sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp)):[]
  const send=async(e)=>{e.preventDefault();if(!text.trim()||!selected)return;const room=rooms.find(r=>r.guest===selected);const row=await secureApi('/api/messages',{method:'POST',body:JSON.stringify({text,receiverId:selected,hostId:room.last.host_id,sessionId:room.last.session_id})});setMessages(old=>[row,...old]);setText('')}
  return <div className="inbox-layout"><aside><h3><Inbox/> Inbox</h3>{rooms.map(r=><button key={r.guest} className={selected===r.guest?'active':''} onClick={()=>setSelected(r.guest)}><span className="avatar">{r.guest.slice(0,2).toUpperCase()}</span><span><b>Customer</b><small>{r.last.text}</small></span>{r.unread>0&&<i>{r.unread}</i>}</button>)}</aside><section>{selected?<><div className="chat-feed">{roomMessages.map(m=><div key={m.id} className={`chat-bubble ${m.sender_id===currentUserId?'mine':''}`}><span>{m.text}</span></div>)}</div><form className="chat-compose" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Reply immediately…"/><button><Send/></button></form></>:<div className="chat-empty"><MessageCircle/><p>Select a customer conversation</p></div>}</section></div>
}

export function SupportModal({ activeSession, close }) {
  const [subject,setSubject]=useState('Cannot Authenticate with Router'),[description,setDescription]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(null),[error,setError]=useState('')
  const submit=async(e)=>{e.preventDefault();setBusy(true);setError('');try{const ticket=await secureApi('/api/tickets',{method:'POST',body:JSON.stringify({hostId:activeSession?.host_id,subject,issueDescription:description})});setDone(ticket)}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <Shell close={close}>{done?<><div className="success-ring"><Check/></div><h2>Ticket received</h2><p>Reference: {done.id}. Customer care will review it shortly.</p><button className="primary wide" onClick={close}>Done</button></>:<form onSubmit={submit}><div className="modal-icon"><Headphones/></div><h2>Customer care</h2><p>Tell us what happened. Your active hotspot is attached automatically.</p><label className="field-label">Issue</label><select className="support-select" value={subject} onChange={e=>setSubject(e.target.value)}>{['Payment Failed but Debited','Cannot Authenticate with Router','Hardware Offline','Slow or Unstable Connection','Other'].map(x=><option key={x}>{x}</option>)}</select><label className="field-label">Description</label><textarea className="support-textarea" minLength={10} maxLength={4000} required value={description} onChange={e=>setDescription(e.target.value)} placeholder="Include what you tried and when it happened."/>{error&&<p className="form-error">{error}</p>}<button className="primary wide" disabled={busy}>{busy?<Loader2 className="spin"/>:'Submit support ticket'}</button></form>}</Shell>
}

export function AdminTicketDashboard() {
  const [tickets,setTickets]=useState([]),[key,setKey]=useState('')
  const load=()=>secureApi('/api/admin/tickets',{headers:{'x-admin-key':key}}).then(setTickets)
  const resolve=async id=>{await secureApi(`/api/admin/tickets/${id}`,{method:'PATCH',headers:{'x-admin-key':key},body:JSON.stringify({status:'resolved',adminNotes:'Resolved by platform support'})});load()}
  return <div><div className="page-heading"><p className="eyebrow">PLATFORM OPERATIONS</p><h1>Customer care center</h1></div><div className="admin-key"><input type="password" placeholder="Admin API key" value={key} onChange={e=>setKey(e.target.value)}/><button className="primary" onClick={load}>Load tickets</button></div><div className="booking-list">{tickets.map(t=><div className="booking-row" key={t.id}><span className="booking-icon"><TicketCheck/></span><div><h3>{t.subject}</h3><p>{t.users?.name} · {t.issue_description}</p><small className={`status ${t.status}`}>{t.status}</small></div>{t.status!=='resolved'&&<button className="secondary" onClick={()=>resolve(t.id)}>Resolve</button>}</div>)}</div></div>
}
