import React, { useEffect, useState } from 'react'
import { Bell, Check, ChevronRight, CircleHelp, CreditCard, Eye, EyeOff, Loader2, LockKeyhole, LogOut, Mail, Moon, Phone, ShieldCheck, UserRound, WalletCards, X } from 'lucide-react'
import { secureApi, supabase } from '../lib/supabase'
import { normalizeNigerianPhone } from '../lib/phone'

const initials = name => String(name||'LB').split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join('').toUpperCase()

export function ProfileDrawer({ user, close, onUpdated, onSupport, onAddMoney, notify }) {
  const [tab,setTab]=useState('account'),[form,setForm]=useState({name:user.name||'',phone:user.phone||'',email:user.email||''}),[password,setPassword]=useState(''),[showPassword,setShowPassword]=useState(false),[methods,setMethods]=useState([]),[loadingCards,setLoadingCards]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const [prefs,setPrefs]=useState(()=>{try{return{notifications:true,connectionAlerts:true,compactMode:false,...JSON.parse(localStorage.getItem('lastbornk_preferences')||'{}')}}catch{return{notifications:true,connectionAlerts:true,compactMode:false}}})
  useEffect(()=>{secureApi('/api/payments/methods').then(setMethods).catch(()=>setMethods([])).finally(()=>setLoadingCards(false))},[])
  const updatePref=(key,value)=>{const next={...prefs,[key]:value};setPrefs(next);localStorage.setItem('lastbornk_preferences',JSON.stringify(next));notify('Preference saved.')}
  const saveProfile=async e=>{e.preventDefault();setBusy(true);setError('');try{const phone=form.phone?normalizeNigerianPhone(form.phone):'';const updated=await secureApi('/api/profile',{method:'PATCH',body:JSON.stringify({...form,phone})});setForm({...form,phone});onUpdated(updated);notify('Account details updated.')}catch(e){setError(e.message)}finally{setBusy(false)}}
  const changePassword=async()=>{if(password.length<8){setError('Password must contain at least 8 characters.');return}setBusy(true);setError('');try{const{error}=await supabase.auth.updateUser({password});if(error)throw error;setPassword('');notify('Password changed successfully.')}catch(e){setError(e.message)}finally{setBusy(false)}}
  const logout=async()=>{await supabase?.auth.signOut();close()}
  return <div className="profile-drawer-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><aside className="profile-drawer">
    <div className="drawer-head"><div><p>MY ACCOUNT</p><h2>Profile & settings</h2></div><button onClick={close}><X/></button></div>
    <div className="drawer-user"><div className="profile-avatar">{initials(user.name)}</div><div><h3>{user.name||'Lastbornk user'}</h3><p>{user.email||user.phone}</p><span><ShieldCheck/> Verified account</span></div></div>
    <nav className="drawer-tabs"><button className={tab==='account'?'active':''} onClick={()=>setTab('account')}><UserRound/>Account</button><button className={tab==='payments'?'active':''} onClick={()=>setTab('payments')}><WalletCards/>Payments</button><button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')}><Bell/>Settings</button></nav>
    <div className="drawer-content">
      {tab==='account'&&<><div className="drawer-section-title"><h3>Account details</h3><p>Keep your personal information up to date.</p></div><form className="profile-form" onSubmit={saveProfile}><label><span><UserRound/> Full name</span><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label><span><Phone/> Phone number</span><input type="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label><span><Mail/> Email address</span><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><button className="primary wide" disabled={busy}>{busy?<Loader2 className="spin"/>:<Check/>} Save changes</button></form><div className="password-box"><div className="drawer-section-title"><h3>Password & security</h3><p>Use at least eight characters.</p></div><div className="password-input"><LockKeyhole/><input type={showPassword?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="New password"/><button onClick={()=>setShowPassword(!showPassword)}>{showPassword?<EyeOff/>:<Eye/>}</button></div><button className="secondary wide" disabled={busy||!password} onClick={changePassword}>Update password</button></div></>}
      {tab==='payments'&&<><div className="drawer-section-title"><h3>Payment methods</h3><p>Cards securely tokenized by Paystack. Full card numbers are never stored by Lastbornk.</p></div>{loadingCards?<div className="drawer-loading"><Loader2 className="spin"/> Loading payment methods…</div>:methods.length?<div className="saved-cards">{methods.map(card=><div className="saved-card" key={card.id}><span><CreditCard/></span><div><b>{card.brand} •••• {card.last4}</b><small>{card.bank}{card.expMonth?` · Expires ${card.expMonth}/${card.expYear}`:''}</small></div>{card.reusable&&<i>Saved</i>}</div>)}</div>:<div className="drawer-empty"><CreditCard/><h3>No saved cards yet</h3><p>Cards that Paystack marks reusable will appear after a successful deposit.</p></div>}<button className="profile-action" onClick={()=>{close();onAddMoney()}}><span><CreditCard/></span><div><b>Add a payment method</b><small>Fund your wallet through Paystack</small></div><ChevronRight/></button></>}
      {tab==='settings'&&<><div className="drawer-section-title"><h3>App settings</h3><p>Choose which updates you want to receive.</p></div><div className="preference-list"><Preference icon={Bell} title="In-app notifications" detail="Deposits, vouchers and account updates" checked={prefs.notifications} onChange={v=>updatePref('notifications',v)}/><Preference icon={CircleHelp} title="Connection alerts" detail="Hotspot connection and disconnection status" checked={prefs.connectionAlerts} onChange={v=>updatePref('connectionAlerts',v)}/><Preference icon={Moon} title="Compact interface" detail="Reduce spacing in data-heavy views" checked={prefs.compactMode} onChange={v=>updatePref('compactMode',v)}/></div><div className="drawer-section-title support-title"><h3>Customer care</h3><p>Our support team can help with payments, routers and sessions.</p></div><button className="profile-action support-action" onClick={()=>{close();onSupport()}}><span><CircleHelp/></span><div><b>Open a support ticket</b><small>Get help from Lastbornk customer care</small></div><ChevronRight/></button></>}
      {error&&<p className="form-error">{error}</p>}
    </div>
    <div className="drawer-footer"><button onClick={logout}><LogOut/> Sign out</button><span>Lastbornk v1.0</span></div>
  </aside></div>
}

function Preference({icon:Icon,title,detail,checked,onChange}){return <div className="preference-row"><span><Icon/></span><div><b>{title}</b><small>{detail}</small></div><button className={`switch ${checked?'on':''}`} role="switch" aria-checked={checked} onClick={()=>onChange(!checked)}><i/></button></div>}
